name: "CI - Build and push with reusable workflow (Production)"

on:
  push:
    branches: [main]
    paths:
      - ./**
      - .github/workflows/ci_prod.yml
  pull_request:
    branches: [main]
    paths:
      - ./**
      - .github/workflows/ci_prod.yml
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build:
    permissions:
      contents: read
      packages: write
    uses: TIHLDE/tihlde-workflows/.github/workflows/_ci_ghcr.yml@v1
    with:
      tag-prefix: ""
      push: ${{ github.event_name != 'pull_request' }}

  deploy:
    needs: build
    if: github.event_name != 'pull_request'
    uses: TIHLDE/tihlde-workflows/.github/workflows/_notify_deploy.yml@v1.1.2
    with:
      image: ghcr.io/${{ github.repository }}
      tag: latest
      environment: prod
    secrets:
      DEPLOY_RECEIVER_TOKEN: ${{ secrets.DEPLOY_RECEIVER_TOKEN }}
